frontend.enableClientVersionCheck:
- value: true
  constraints: {}
system.minRetentionDays:
- value: 0
  constraints: {}
history.EnableConsistentQueryByDomain:
- value: true
  constraints: {}
worker.executionsScannerEnabled:
  - value: true
    constraints: {}
worker.executionsScannerInvariantCollectionMutableState:
  - value: true
    constraints: {}
worker.executionsScannerInvariantCollectionHistory:
  - value: true
    constraints: {}
worker.concreteExecutionFixerEnabled:
  - value: true
    constraints: {}
worker.concreteExecutionFixerDomainAllow:
  - value: true
    constraints: {}